// Battery walkthrough (v3): BT-1..BT-4, ST-1..ST-3 + sampler/history, helper states, fail-safe, wake. Usage: node tools/test-battery.js
const path = require('path');
const { chromium } = require(process.env.PW || '/tmp/pw/node_modules/playwright');
let n = 0;
const ok = (c, m) => { if (!c) throw new Error('FAIL: ' + m); console.log('  ok  ' + m); };
(async () => {
  const b = await chromium.launch({ channel: process.env.PW_CHANNEL || undefined });
  const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
  const errs = [];
  p.on('pageerror', (e) => errs.push('pageerror: ' + e.message));
  p.on('console', (m) => m.type() === 'error' && errs.push('console: ' + m.text()));
  const url = 'file://' + path.resolve(__dirname, '../index.html');
  await p.goto(url);
  await p.waitForTimeout(500);
  const shot = (name) => p.screenshot({ path: `/tmp/v3-battery-${String(++n).padStart(2, '0')}-${name}.png` });
  const txt = (s) => p.evaluate((s) => (document.querySelector(s) || {}).textContent || '', s);
  const setRange = (sel, v) => p.evaluate(([s, v]) => { const e = document.querySelector(s); e.value = v; e.dispatchEvent(new Event('input', { bubbles: true })); }, [sel, v]);
  const popOpen = async () => { if (await p.$('#pop:not([hidden]) .bt-pop')) return; await p.click('[data-mb=battery]'); await p.waitForSelector('#pop .bt-pop'); };
  const popClose = async () => { await p.keyboard.press('Escape'); };
  const scn = async (key) => { await p.click('[data-mb=scn]'); await p.click(`[data-s="${key}"]`); await p.keyboard.press('Escape'); };
  const setScn = (k, v) => p.evaluate(([k, v]) => OS.setScn(k, v), [k, v]);
  const charge = () => p.evaluate(() => OS.data.battery.charge);
  const pref = (k) => p.evaluate((k) => OS.pref(k), k);
  const aria = (s) => p.getAttribute(s, 'aria-checked');
  const points = () => p.$$eval('[data-line]', (e) => e[0].getAttribute('points').split(' ').length);
  const installHelper = async () => { await p.click('[data-grant]'); await p.click('#dlg [data-r="1"]'); await p.waitForSelector('#dlg', { state: 'hidden' }); };
  const openView = async () => { await p.click('#pop [data-set]'); await p.waitForSelector('.bt-view .bt-main .bt-note'); };

  console.log('BT-1 menubar + popover + sampler card');
  ok(/62%/.test(await txt('[data-mb=battery]')), 'menubar shows 62%');
  await popOpen();
  let t = await txt('#pop');
  ok(/62%/.test(t) && /Charging · .* to 100%/.test(t), 'popover: charge + charging estimate (limit off)');
  ok(/Sampled \d+ s ago/.test(t), 'popover: "Sampled N s ago"');
  ok(/Power adapter/.test(t) && /33 °C/.test(t), 'popover: power source + temperature');
  ok(/Battery Settings…/.test(t), 'footer has Battery Settings…');
  ok(!!(await p.$('#pop .bt-bar')), 'bar present');
  ok(!/Helper \d/.test(t), 'no helper version while the helper is not installed');
  console.log('ST-2 helper missing');
  ok(!!(await p.$('#pop .state.permission.missing')) && /Add Helper/.test(t) && !(await p.$('#pop [data-ls]')), 'popover: Add Helper card replaces the limit control');
  await shot('popover-helper-missing');

  console.log('BT-2 limit from popover');
  await installHelper();
  ok(!!(await p.$('#pop [data-ls]')) && !(await p.$('#pop .state.permission')), 'after install: toggle + slider replace the grant');
  ok(/Helper 1\.1\.0/.test(await txt('#pop')), 'popover footer shows helper version 1.1.0');
  ok((await p.getAttribute('#pop [data-ls]', 'step')) === '5' && (await p.getAttribute('#pop [data-ls]', 'min')) === '50', 'slider 50-100 step 5');
  ok(await p.isDisabled('#pop [data-ls]'), 'slider disabled while limit off');
  await p.click('#pop [data-lt]');
  ok((await pref('battery.limitOn')) === true && (await aria('#pop [data-lt]')) === 'true', 'toggle on sets pref');
  await setRange('#pop [data-ls]', 70);
  ok((await pref('battery.limit')) === 70, 'slider sets pref limit=70');
  ok(/Charging · .* to 70%/.test(await txt('#pop')), 'state line targets 70%');
  ok(await p.$eval('#pop [data-mark]', (e) => e.style.left === '70%' && !e.hidden), 'limit marker at 70%');
  await shot('popover-limit-on');

  console.log('BT-2 popover -> view');
  await openView();
  ok((await aria('.pane [data-k="battery.limitOn"]')) === 'true' && (await p.inputValue('.pane [data-k="battery.limit"]')) === '70', 'pane reflects popover (on, 70)');
  ok((await p.getAttribute('[data-limit-line]', 'data-limit')) === '70' && (await p.getAttribute('[data-limit-line]', 'data-on')) === 'true', 'chart limit line at 70, active');
  ok(/Helper 1\.1\.0/.test(await txt('.pane')), 'view pane footer shows helper version');
  await shot('view');

  console.log('BT-2 view pane -> popover');
  await setRange('.pane [data-k="battery.limit"]', 60);
  ok((await p.getAttribute('[data-limit-line]', 'data-limit')) === '60', 'chart line moved to 60');
  await popOpen();
  ok(/Holding at 60%/.test(await txt('#pop')) && (await p.inputValue('#pop [data-ls]')) === '60', 'popover: Holding at 60%');
  await shot('popover-holding');
  const c0 = await charge(); await p.waitForTimeout(4600);
  ok((await charge()) === c0, 'holding: charge does not move on ticks');

  console.log('live: pref changed elsewhere updates the open popover');
  await p.evaluate(() => OS.setPref('battery.limit', 90));
  ok((await p.inputValue('#pop [data-ls]')) === '90' && /to 90%/.test(await txt('#pop')), 'open popover follows pref (90)');
  await p.click('#pop [data-lt]');
  ok((await pref('battery.limitOn')) === false, 'popover toggle off');
  await openView();
  ok((await aria('.pane [data-k="battery.limitOn"]')) === 'false' && (await p.getAttribute('[data-limit-line]', 'data-on')) === 'false', 'view agrees: off, chart line inactive');

  console.log('BT-2 Preferences -> popover');
  await p.click('[data-go=prefs]');
  await p.waitForSelector('#prefwin:not([hidden]) .ptabs');
  await p.click('#prefwin [data-pane=battery]');
  await p.waitForSelector('#prefs [data-k="battery.limitOn"]');
  await p.click('#prefs [data-k="battery.limitOn"]');
  await setRange('#prefs [data-k="battery.limit"]', 75);
  ok((await pref('battery.limitOn')) === true && (await pref('battery.limit')) === 75, 'Preferences sets limitOn + 75');
  ok(/Charging holds at the limit/.test(await txt('#prefs')) && /5-minute samples for 24 h and hourly samples for 7 days/.test(await txt('#prefs')) && /samples/.test(await txt('#prefs')), 'prefs rows show effect lines; Data row shows sampling rule + count');
  await shot('preferences');
  await popOpen();
  ok((await aria('#pop [data-lt]')) === 'true' && (await p.inputValue('#pop [data-ls]')) === '75', 'popover reflects Preferences');
  await popClose();
  ok(/Storage/.test(await txt('#prefwin')), 'Preferences window has a Storage pane');
  await p.click('#prefwin [data-pane=storage]');
  ok(/\d+ samples/.test(await txt('#prefs')), 'Storage pane lists battery samples');

  console.log('BT-3 hot pauses charging');
  await scn('battery.hot');
  await popOpen();
  t = await txt('#pop');
  ok(/Paused — Mac is hot/.test(t) && /41 °C/.test(t), 'popover: Paused — Mac is hot, 41 °C');
  ok(await p.$eval('#pop .bt-fill', (e) => e.classList.contains('paused')), 'bar tinted as paused');
  await shot('popover-paused-hot');
  const c1 = await charge(); await p.waitForTimeout(4600);
  ok((await charge()) === c1, 'paused: charge holds while hot');
  await openView();
  ok(/Paused — hot/.test(await txt('.bt-note')) && /41 °C/.test(await txt('[data-v=temp]')), 'view shows Paused — hot, 41 °C');
  await setRange('.pane [data-k="battery.limit"]', 100);
  await p.click('.pane [data-k="battery.limitOn"]'); // off: charge may rise once hot clears
  await p.click('.pane [data-k="battery.pauseHot"]');
  ok((await pref('battery.pauseHot')) === false, 'pauseHot off');
  await p.waitForTimeout(4600);
  ok((await charge()) > c1, 'charging continues when pause-when-hot is off');
  await p.click('.pane [data-k="battery.pauseHot"]');
  await scn('battery.hot');

  console.log('G5 helper states');
  await p.click('.pane [data-k="battery.limitOn"]');   // limit on again
  ok((await pref('battery.limitOn')) === true, 'limit on');
  await setScn('perm.helperApproval', true);
  await popOpen();
  ok(!!(await p.$('#pop .state.permission.approval')) && /Open Login Items/.test(await txt('#pop')) && !(await p.$('#pop [data-ls]')), 'approval: Login Items card replaces the limit control');
  ok(/Limit off — helper needs approval/.test(await txt('#pop')), 'approval: state line says the limit is off');
  await shot('popover-helper-approval');
  await openView();
  ok(!!(await p.$('.pane .state.approval')) && !(await p.$('.pane [data-k="battery.limit"]')), 'approval: view pane shows the card, no dead limit control');
  await shot('view-helper-approval');
  await p.click('.pane [data-grant]');                // Login Items dialog
  await p.click('#dlg [data-t]'); await p.click('#dlg [data-r="done"]'); await p.waitForSelector('#dlg', { state: 'hidden' });
  ok((await p.evaluate(() => OS.perm.state('helper'))) === 'granted' && !!(await p.$('.pane [data-k="battery.limit"]')), 'approving in Login Items restores the limit control');
  await setScn('perm.helperOutdated', true);
  ok(!!(await p.$('.pane .state.outdated')) && /1\.0\.2/.test(await txt('.pane')) && /1\.1\.0/.test(await txt('.pane')), 'outdated: card names 1.0.2 and 1.1.0');
  ok(/Limit off — helper 1\.0\.2 needs updating/.test(await txt('.bt-note')), 'outdated: status line');
  await shot('view-helper-outdated');
  await p.click('.pane [data-grant]'); await p.click('#dlg [data-r="1"]'); await p.waitForSelector('#dlg', { state: 'hidden' });
  ok((await p.evaluate(() => OS.perm.state('helper'))) === 'granted', 'Update Helper clears the outdated state');
  await setScn('perm.unsupported', true);
  ok(!!(await p.$('.pane .state.unsupported')) && /isn’t available on this Mac/.test(await txt('.pane')) && !(await p.$('.pane [data-k="battery.limit"]')), 'unsupported: reason shown, limit controls gone');
  ok(!/Limit off/.test(await txt('.bt-note')), 'unsupported: no "Limit off" claim; charging is macOS-managed');
  await popOpen();
  ok(!!(await p.$('#pop .state.unsupported')) && !(await p.$('#pop [data-ls]')), 'unsupported: popover shows the reason instead of controls');
  await shot('popover-unsupported');
  await setScn('perm.unsupported', false);
  await popClose();

  console.log('fail-safe: charge helper stops responding');
  await scn('battery.helperDisconnect');
  await popOpen();
  t = await txt('#pop');
  ok(/Charging is back under macOS control/.test(t) && !!(await p.$('#pop [data-rc]')), 'popover: back under macOS control + Reconnect');
  ok(!(await p.$('#pop .state.failure')) && !(await p.$('#pop .bt-fill.paused')), 'safety tone, not an error state');
  ok(await p.isDisabled('#pop [data-ls]'), 'popover: limit slider disabled while helper is down');
  await shot('popover-failsafe');
  await openView();
  ok(/Charging is back under macOS control/.test(await txt('.bt-note')) && !!(await p.$('.bt-note [data-rc]')) && !(await p.$('.bt-note .tag.bad')) && !(await p.$('.bt-note .tag.warn')), 'view: banner with Reconnect, no error tag');
  ok(await p.$eval('.bt-locked > div', (e) => e.inert), 'view: limit controls inert with a reason');
  ok(/Available again when the helper reconnects/.test(await txt('.pane')), 'view: reason for disabled controls');
  await setScn('notes', true);
  ok(/invalidationHandler/.test(await txt('.bt-main')) && await p.$eval('.bt-main .cn', (e) => getComputedStyle(e).display !== 'none'), 'contract note: XPC invalidationHandler → .failSafe visible with notes on');
  await shot('view-failsafe');
  await setScn('notes', false);
  await p.click('.bt-note [data-rc]');
  ok(!(await p.evaluate(() => OS.scn('battery.helperDisconnect'))) && !/macOS control/.test(await txt('.bt-note')), 'Reconnect clears it');
  ok(!!(await p.$('.pane [data-k="battery.limit"]')) && !(await p.$('.bt-locked')), 'limit controls are back');

  console.log('wake: limit re-applied');
  await setRange('.pane [data-k="battery.limit"]', 60);
  ok(/Holding at 60%/.test(await txt('.bt-note')), 'holding before sleep');
  await scn('battery.wake');
  ok(/Re-applying limit…/.test(await txt('.bt-note')), 'wake: Re-applying limit…');
  await popOpen();
  ok(/Re-applying limit…/.test(await txt('#pop')), 'wake: popover also says Re-applying limit…');
  await shot('popover-wake');
  await p.waitForFunction(() => !OS.scn('battery.wake'), null, { timeout: 5000 });
  ok(/Holding at 60%/.test(await txt('.bt-note')) && /Holding at 60%/.test(await txt('#pop')), 'wake: back to Holding at 60%');
  await popClose();
  await p.click('.pane [data-k="battery.limitOn"]');   // off: charging not capped for the rest of the run

  console.log('on battery + showPercent');
  await scn('battery.unplugged');
  await popOpen();
  ok(/On battery · \d+ h/.test(await txt('#pop')) && /Battery/.test(await txt('#pop [data-src]')), 'popover: On battery · N h left, source Battery');
  const c2 = await charge(); await p.waitForTimeout(4600);
  ok((await charge()) < c2, 'unplugged: charge drops on ticks');
  await shot('popover-on-battery');
  await openView();
  ok(/Battery/.test(await txt('[data-v=source]')) && /On battery/.test(await txt('[data-v=state]')), 'view sample card: source Battery, state On battery');
  await p.click('.pane [data-k="battery.showPercent"]');
  ok((await txt('[data-mb=battery]')).trim() === '', 'menubar percent hidden when showPercent off');
  await p.click('.pane [data-k="battery.showPercent"]');
  ok(/\d+%/.test(await txt('[data-mb=battery]')), 'menubar percent back on');
  await scn('battery.unplugged');

  console.log('BT-4 + G7 sampler + history');
  await p.click('[data-go=battery]'); await p.waitForSelector('.bt-chart svg');
  ok(/Sampled \d+ s ago/.test(await txt('.bt-sample')) && /Updates when power changes; temperature every minute/.test(await txt('.bt-sample')), 'sample card: age + update cadence copy');
  ok(/Shown every 5 minutes for 24 h, hourly for 7 days, then removed/.test(await txt('.bt-hist')), 'history copy states the prune rule');
  const p24 = await points();
  ok(p24 >= 280 && p24 <= 300, '24 h chart has ~5-minute samples (' + p24 + ')');
  await p.click('.seg [data-r=d7]');
  const p7 = await points();
  ok(p7 > p24 && p7 <= 450, '7 d chart adds hourly samples (' + p7 + ')');
  ok(/%/.test(await txt('[data-v=health]')) && /^\d+$/.test((await txt('[data-v=cycles]')).trim()), 'health % and cycles shown');
  await shot('view-7d');
  await p.click('.seg [data-r=h24]');
  const before = await p.evaluate(() => OS.data.battery.hist.length);
  await p.click('[data-sample]');
  ok((await p.evaluate(() => OS.data.battery.hist.length)) === before + 1, 'Sample now appends a sample');
  const lastT = () => p.evaluate(() => OS.data.battery.hist[OS.data.battery.hist.length - 1].t);
  const t0 = await lastT();
  await p.evaluate(() => OS.skip(5 * 60000));
  ok((await lastT()) - t0 >= 5 * 60000 - 1000, 'simulated clock skip appends a sample on the simulated clock');
  await p.evaluate(() => { OS.skip(86400000); OS.skip(86400000); OS.skip(86400000 * 4); });
  const bound = await p.evaluate(() => ({ n: OS.data.battery.hist.length, old: OS.now() - OS.data.battery.hist[0].t, sorted: OS.data.battery.hist.every((s, i, a) => !i || s.t >= a[i - 1].t) }));
  ok(bound.n <= 450 && bound.old <= 7 * 86400000 && bound.sorted, 'history stays bounded: ' + bound.n + ' samples, oldest ' + Math.round(bound.old / 3600000) + ' h');
  const thin = await p.evaluate(() => { const c = OS.now() - 86400000 - 120000; const old = OS.data.battery.hist.filter((s) => s.t < c).map((s) => Math.floor(s.t / 3600000)); return old.length === new Set(old).size; });
  ok(thin, 'samples older than 24 h are hourly' + (thin ? '' : ' ' + JSON.stringify(await p.evaluate(() => { const c = OS.now() - 86400000 - 120000; const seen = {}; return OS.data.battery.hist.filter((s) => s.t < c).filter((s) => { const k = Math.floor(s.t / 3600000); const d = seen[k]; seen[k] = 1; return d; }).map((s) => [(c - s.t) / 60000, s.t % 3600000]); }))));
  ok(/\d+ samples kept/.test(await txt('[data-count]')), 'toolbar shows the sample count');

  console.log('G10 menus: no selection in this view');
  await p.click('#win .bt-main');
  const edit = await p.evaluate(() => OS.menus().find((m) => m.id === 'edit').items.filter((i) => i !== '-').map((i) => [i.label, i.enabled()]));
  ok(edit.length >= 4 && edit.every(([, e]) => !e), 'Edit menu items are all disabled (nothing selectable in Battery)');
  await p.click('#mbL [data-menu=edit]');
  ok((await p.$$('#menu button[disabled]')).length >= 4, 'Edit menu draws them disabled');
  await p.keyboard.press('Escape');

  console.log('ST-1 empty / info / failure');
  await scn('battery.empty');
  await p.click('[data-go=battery]'); await p.waitForSelector('.bt-view .bt-note');
  ok(!!(await p.$('.bt-chart .state.info')) && /History fills in as OneShot runs/.test(await txt('.bt-chart')), 'short history: History fills in as OneShot runs');
  await shot('view-empty');
  await scn('battery.empty');
  await scn('battery.fail');
  await popOpen();
  ok(!!(await p.$('#pop .state.failure')) && !(await p.$('#pop .bt-big')) && /Try again/.test(await txt('#pop')), 'popover shows the store failure instead of data');
  await shot('popover-store-fail');
  await popClose();
  await p.click('[data-go=battery]'); await p.waitForSelector('.state.failure');
  ok(/Couldn’t open Battery/.test(await txt('#view')), 'failure state shown');
  await shot('view-failure');
  await scn('battery.fail');
  await p.click('#view [data-act]'); await p.waitForSelector('.bt-view .bt-note');
  ok(true, 'Try Again recovers');

  console.log('G1 reload persists data and prefs');
  await p.evaluate(() => { OS.setPref('battery.limit', 85); });
  await p.click('[data-sample]');
  const kept = await p.evaluate(() => OS.data.battery.hist.length);
  await p.waitForTimeout(500);
  await p.reload(); await p.waitForTimeout(600);
  ok((await pref('battery.limit')) === 85, 'pref survived reload');
  ok((await p.evaluate(() => OS.data.battery.hist.length)) >= kept, 'history survived reload (' + kept + ' samples)');
  ok((await p.evaluate(() => OS.perm.state('helper'))) === 'granted', 'helper grant survived reload');
  await p.evaluate(() => OS.open('battery')); await p.waitForSelector('.bt-chart svg');
  ok(/Sampled \d+ s ago/.test(await txt('.bt-sample')), 'sampled age resets on launch');

  ok(errs.length === 0, 'no console errors' + (errs.length ? ': ' + errs.join(' | ') : ''));
  await b.close();
  console.log('battery: all passed');
})().catch((e) => { console.error(e.message); process.exit(1); });
